sphinx documentation generation

diff --git a/.github/workflows/tagged_master_release.yml b/.github/workflows/tagged_master_release.yml
--- a/.github/workflows/tagged_master_release.yml
+++ b/.github/workflows/tagged_master_release.yml
@@ -14,11 +14,8 @@ jobs:
 
     steps:
       - uses: actions/checkout@v2
-      - name: Checkout submodules
-        shell: bash
-        run: |
-          git submodule sync --recursive
-          git submodule update --init --force --recursive --depth=50
+        with:
+          submodules: "recursive"
       - uses: ilammy/msvc-dev-cmd@v1.2.0
       - name: Install Python 3.8 version
         uses: actions/setup-python@v1
@@ -102,6 +99,36 @@ jobs:
           name: agave-win
           path: ./build/agave-win.zip
 
+  docs:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          submodules: "recursive"
+      - uses: ammaraskar/sphinx-action@master
+        with:
+          docs-folder: "docs/"
+      - uses: actions/upload-artifact@v1
+        with:
+          name: DocumentationHTML
+          path: docs/_build/html/
+      - name: Commit documentation changes
+        run: |
+          git clone https://github.com/allen-cell-animated/agave.git --branch gh-pages --single-branch gh-pages
+          cp -r docs/_build/html/* gh-pages/
+          cd gh-pages
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add .
+          git commit -m "Update documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # the return code.
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          directory: gh-pages
+          github_token: ${{ secrets.GITHUB_TOKEN }}          
   make-release:
     runs-on: ubuntu-latest
     needs: cmake-build
